# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GrpcKommunikation.util_pb2 as util__pb2
import GrpcKommunikation.metadata_pb2 as metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x1a\nutil.proto\x1a\x0emetadata.proto\"e\n\tAudioData\x12\x15\n\rreferenceNano\x18\x01 \x01(\x04\x12\x12\n\nsampleRate\x18\x02 \x01(\r\x12\x1c\n\x06\x66ormat\x18\x03 \x01(\x0e\x32\x0c.AudioFormat\x12\x0f\n\x07samples\x18\x04 \x01(\x0c\":\n\x11\x41\x63\x63\x65lerometerData\x12%\n\x07samples\x18\x01 \x03(\x0b\x32\x14.AccelerometerSample\"M\n\x13\x41\x63\x63\x65lerometerSample\x12\x15\n\rreferenceNano\x18\x01 \x01(\x04\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02*G\n\x0b\x41udioFormat\x12\x1a\n\x16\x41UDIO_FORMAT_UNDEFINED\x10\x00\x12\r\n\tLINEAR_16\x10\x01\x12\r\n\tLINEAR_32\x10\x02\x42\x36\n)com.daimler.smartfactory.anne.model.protoB\tDataProtob\x06proto3')

_AUDIOFORMAT = DESCRIPTOR.enum_types_by_name['AudioFormat']
AudioFormat = enum_type_wrapper.EnumTypeWrapper(_AUDIOFORMAT)
AUDIO_FORMAT_UNDEFINED = 0
LINEAR_16 = 1
LINEAR_32 = 2


_AUDIODATA = DESCRIPTOR.message_types_by_name['AudioData']
_ACCELEROMETERDATA = DESCRIPTOR.message_types_by_name['AccelerometerData']
_ACCELEROMETERSAMPLE = DESCRIPTOR.message_types_by_name['AccelerometerSample']
AudioData = _reflection.GeneratedProtocolMessageType('AudioData', (_message.Message,), {
  'DESCRIPTOR' : _AUDIODATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:AudioData)
  })
_sym_db.RegisterMessage(AudioData)

AccelerometerData = _reflection.GeneratedProtocolMessageType('AccelerometerData', (_message.Message,), {
  'DESCRIPTOR' : _ACCELEROMETERDATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:AccelerometerData)
  })
_sym_db.RegisterMessage(AccelerometerData)

AccelerometerSample = _reflection.GeneratedProtocolMessageType('AccelerometerSample', (_message.Message,), {
  'DESCRIPTOR' : _ACCELEROMETERSAMPLE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:AccelerometerSample)
  })
_sym_db.RegisterMessage(AccelerometerSample)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.daimler.smartfactory.anne.model.protoB\tDataProto'
  _AUDIOFORMAT._serialized_start=284
  _AUDIOFORMAT._serialized_end=355
  _AUDIODATA._serialized_start=42
  _AUDIODATA._serialized_end=143
  _ACCELEROMETERDATA._serialized_start=145
  _ACCELEROMETERDATA._serialized_end=203
  _ACCELEROMETERSAMPLE._serialized_start=205
  _ACCELEROMETERSAMPLE._serialized_end=282
# @@protoc_insertion_point(module_scope)
