# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GrpcKommunikation.metadata_pb2 as metadata__pb2
import GrpcKommunikation.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\x12\x11logbee.anne.model\x1a\x0emetadata.proto\x1a\nutil.proto\"$\n\rLogProducerId\x12\x13\n\x04uuid\x18\x01 \x01(\x0b\x32\x05.UUID\"S\n\x15LogProducerDescriptor\x12,\n\x02id\x18\x01 \x01(\x0b\x32 .logbee.anne.model.LogProducerId\x12\x0c\n\x04name\x18\x02 \x01(\t\"d\n\x08LogEvent\x12\x1d\n\nproperties\x18\x03 \x03(\x0b\x32\t.Property\x12.\n\x04text\x18\x0f \x01(\x0b\x32\x1e.logbee.anne.model.TextPayloadH\x00\x42\t\n\x07payload\"X\n\x0bTextPayload\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12*\n\x05level\x18\x03 \x01(\x0e\x32\x1b.logbee.anne.model.LogLevel*[\n\x08LogLevel\x12\x17\n\x13LOG_LEVEL_UNDEFINED\x10\x00\x12\t\n\x05\x45rror\x10\x01\x12\x0b\n\x07Warning\x10\x02\x12\x08\n\x04Info\x10\x03\x12\t\n\x05\x44\x65\x62ug\x10\x04\x12\t\n\x05Trace\x10\x05\x42\x39\n)com.daimler.smartfactory.anne.model.protoB\x0cLoggingProtob\x06proto3')

_LOGLEVEL = DESCRIPTOR.enum_types_by_name['LogLevel']
LogLevel = enum_type_wrapper.EnumTypeWrapper(_LOGLEVEL)
LOG_LEVEL_UNDEFINED = 0
Error = 1
Warning = 2
Info = 3
Debug = 4
Trace = 5


_LOGPRODUCERID = DESCRIPTOR.message_types_by_name['LogProducerId']
_LOGPRODUCERDESCRIPTOR = DESCRIPTOR.message_types_by_name['LogProducerDescriptor']
_LOGEVENT = DESCRIPTOR.message_types_by_name['LogEvent']
_TEXTPAYLOAD = DESCRIPTOR.message_types_by_name['TextPayload']
LogProducerId = _reflection.GeneratedProtocolMessageType('LogProducerId', (_message.Message,), {
  'DESCRIPTOR' : _LOGPRODUCERID,
  '__module__' : 'logging_pb2'
  # @@protoc_insertion_point(class_scope:logbee.anne.model.LogProducerId)
  })
_sym_db.RegisterMessage(LogProducerId)

LogProducerDescriptor = _reflection.GeneratedProtocolMessageType('LogProducerDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _LOGPRODUCERDESCRIPTOR,
  '__module__' : 'logging_pb2'
  # @@protoc_insertion_point(class_scope:logbee.anne.model.LogProducerDescriptor)
  })
_sym_db.RegisterMessage(LogProducerDescriptor)

LogEvent = _reflection.GeneratedProtocolMessageType('LogEvent', (_message.Message,), {
  'DESCRIPTOR' : _LOGEVENT,
  '__module__' : 'logging_pb2'
  # @@protoc_insertion_point(class_scope:logbee.anne.model.LogEvent)
  })
_sym_db.RegisterMessage(LogEvent)

TextPayload = _reflection.GeneratedProtocolMessageType('TextPayload', (_message.Message,), {
  'DESCRIPTOR' : _TEXTPAYLOAD,
  '__module__' : 'logging_pb2'
  # @@protoc_insertion_point(class_scope:logbee.anne.model.TextPayload)
  })
_sym_db.RegisterMessage(TextPayload)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.daimler.smartfactory.anne.model.protoB\014LoggingProto'
  _LOGLEVEL._serialized_start=379
  _LOGLEVEL._serialized_end=470
  _LOGPRODUCERID._serialized_start=64
  _LOGPRODUCERID._serialized_end=100
  _LOGPRODUCERDESCRIPTOR._serialized_start=102
  _LOGPRODUCERDESCRIPTOR._serialized_end=185
  _LOGEVENT._serialized_start=187
  _LOGEVENT._serialized_end=287
  _TEXTPAYLOAD._serialized_start=289
  _TEXTPAYLOAD._serialized_end=377
# @@protoc_insertion_point(module_scope)
