# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GrpcKommunikation.logging_collector_pb2 as logging__collector__pb2


class LoggingCollectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.logs = channel.stream_stream(
                '/logbee.anne.carl.logging.LoggingCollector/logs',
                request_serializer=logging__collector__pb2.LoggingDownstream.SerializeToString,
                response_deserializer=logging__collector__pb2.LoggingUpstream.FromString,
                )


class LoggingCollectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def logs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggingCollectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'logs': grpc.stream_stream_rpc_method_handler(
                    servicer.logs,
                    request_deserializer=logging__collector__pb2.LoggingDownstream.FromString,
                    response_serializer=logging__collector__pb2.LoggingUpstream.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logbee.anne.carl.logging.LoggingCollector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LoggingCollector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def logs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/logbee.anne.carl.logging.LoggingCollector/logs',
            logging__collector__pb2.LoggingDownstream.SerializeToString,
            logging__collector__pb2.LoggingUpstream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
