# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\"\xa1\x01\n\x08Property\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x04text\x18\x0f \x01(\x0b\x32\n.TextValueH\x00\x12\x1e\n\x06number\x18\x0e \x01(\x0b\x32\x0c.NumberValueH\x00\x12 \n\x07\x64\x65\x63imal\x18\r \x01(\x0b\x32\r.DecimalValueH\x00\x12 \n\x07\x62oolean\x18\x0c \x01(\x0b\x32\r.BooleanValueH\x00\x42\x07\n\x05value\"\x1d\n\x0c\x42ooleanValue\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1c\n\x0bNumberValue\x12\r\n\x05value\x18\x01 \x01(\x03\"\x1d\n\x0c\x44\x65\x63imalValue\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1a\n\tTextValue\x12\r\n\x05value\x18\x01 \x01(\tB-\n)com.daimler.smartfactory.anne.model.protoP\x01\x62\x06proto3')



_PROPERTY = DESCRIPTOR.message_types_by_name['Property']
_BOOLEANVALUE = DESCRIPTOR.message_types_by_name['BooleanValue']
_NUMBERVALUE = DESCRIPTOR.message_types_by_name['NumberValue']
_DECIMALVALUE = DESCRIPTOR.message_types_by_name['DecimalValue']
_TEXTVALUE = DESCRIPTOR.message_types_by_name['TextValue']
Property = _reflection.GeneratedProtocolMessageType('Property', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTY,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:Property)
  })
_sym_db.RegisterMessage(Property)

BooleanValue = _reflection.GeneratedProtocolMessageType('BooleanValue', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANVALUE,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:BooleanValue)
  })
_sym_db.RegisterMessage(BooleanValue)

NumberValue = _reflection.GeneratedProtocolMessageType('NumberValue', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERVALUE,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:NumberValue)
  })
_sym_db.RegisterMessage(NumberValue)

DecimalValue = _reflection.GeneratedProtocolMessageType('DecimalValue', (_message.Message,), {
  'DESCRIPTOR' : _DECIMALVALUE,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:DecimalValue)
  })
_sym_db.RegisterMessage(DecimalValue)

TextValue = _reflection.GeneratedProtocolMessageType('TextValue', (_message.Message,), {
  'DESCRIPTOR' : _TEXTVALUE,
  '__module__' : 'metadata_pb2'
  # @@protoc_insertion_point(class_scope:TextValue)
  })
_sym_db.RegisterMessage(TextValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.daimler.smartfactory.anne.model.protoP\001'
  _PROPERTY._serialized_start=19
  _PROPERTY._serialized_end=180
  _BOOLEANVALUE._serialized_start=182
  _BOOLEANVALUE._serialized_end=211
  _NUMBERVALUE._serialized_start=213
  _NUMBERVALUE._serialized_end=241
  _DECIMALVALUE._serialized_start=243
  _DECIMALVALUE._serialized_end=272
  _TEXTVALUE._serialized_start=274
  _TEXTVALUE._serialized_end=300
# @@protoc_insertion_point(module_scope)
