# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recording.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GrpcKommunikation.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecording.proto\x1a\nutil.proto\"\"\n\x0bRecordingId\x12\x13\n\x04uuid\x18\x01 \x01(\x0b\x32\x05.UUIDB;\n)com.daimler.smartfactory.anne.model.protoB\x0eRecordingProtob\x06proto3')



_RECORDINGID = DESCRIPTOR.message_types_by_name['RecordingId']
RecordingId = _reflection.GeneratedProtocolMessageType('RecordingId', (_message.Message,), {
  'DESCRIPTOR' : _RECORDINGID,
  '__module__' : 'recording_pb2'
  # @@protoc_insertion_point(class_scope:RecordingId)
  })
_sym_db.RegisterMessage(RecordingId)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.daimler.smartfactory.anne.model.protoB\016RecordingProto'
  _RECORDINGID._serialized_start=31
  _RECORDINGID._serialized_end=65
# @@protoc_insertion_point(module_scope)
