# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GrpcKommunikation.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstream.proto\x1a\nutil.proto\"3\n\nStreamInit\x12%\n\nconditions\x18\x01 \x01(\x0b\x32\x11.StreamConditions\")\n\x10StreamConditions\x12\x15\n\rhasBeenPulled\x18\x01 \x01(\x08\",\n\x12StreamInitComplete\x12\x16\n\x07session\x18\x01 \x01(\x0b\x32\x05.UUID\"\x12\n\x10\x44ownstreamFinish\"\x15\n\x13\x44ownstreamFinishAck\"\"\n\x11\x44ownstreamFailure\x12\r\n\x05\x63\x61use\x18\x01 \x01(\t\"\x16\n\x14\x44ownstreamFailureAck\"\x10\n\x0eUpstreamFinish\"\x13\n\x11UpstreamFinishAck\" \n\x0fUpstreamFailure\x12\r\n\x05\x63\x61use\x18\x01 \x01(\t\"\x14\n\x12UpstreamFailureAckB@\n0com.daimler.smartfactory.anne.streams.grpc.protoB\x0cStreamsProtob\x06proto3')



_STREAMINIT = DESCRIPTOR.message_types_by_name['StreamInit']
_STREAMCONDITIONS = DESCRIPTOR.message_types_by_name['StreamConditions']
_STREAMINITCOMPLETE = DESCRIPTOR.message_types_by_name['StreamInitComplete']
_DOWNSTREAMFINISH = DESCRIPTOR.message_types_by_name['DownstreamFinish']
_DOWNSTREAMFINISHACK = DESCRIPTOR.message_types_by_name['DownstreamFinishAck']
_DOWNSTREAMFAILURE = DESCRIPTOR.message_types_by_name['DownstreamFailure']
_DOWNSTREAMFAILUREACK = DESCRIPTOR.message_types_by_name['DownstreamFailureAck']
_UPSTREAMFINISH = DESCRIPTOR.message_types_by_name['UpstreamFinish']
_UPSTREAMFINISHACK = DESCRIPTOR.message_types_by_name['UpstreamFinishAck']
_UPSTREAMFAILURE = DESCRIPTOR.message_types_by_name['UpstreamFailure']
_UPSTREAMFAILUREACK = DESCRIPTOR.message_types_by_name['UpstreamFailureAck']
StreamInit = _reflection.GeneratedProtocolMessageType('StreamInit', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINIT,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamInit)
  })
_sym_db.RegisterMessage(StreamInit)

StreamConditions = _reflection.GeneratedProtocolMessageType('StreamConditions', (_message.Message,), {
  'DESCRIPTOR' : _STREAMCONDITIONS,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamConditions)
  })
_sym_db.RegisterMessage(StreamConditions)

StreamInitComplete = _reflection.GeneratedProtocolMessageType('StreamInitComplete', (_message.Message,), {
  'DESCRIPTOR' : _STREAMINITCOMPLETE,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamInitComplete)
  })
_sym_db.RegisterMessage(StreamInitComplete)

DownstreamFinish = _reflection.GeneratedProtocolMessageType('DownstreamFinish', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAMFINISH,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:DownstreamFinish)
  })
_sym_db.RegisterMessage(DownstreamFinish)

DownstreamFinishAck = _reflection.GeneratedProtocolMessageType('DownstreamFinishAck', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAMFINISHACK,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:DownstreamFinishAck)
  })
_sym_db.RegisterMessage(DownstreamFinishAck)

DownstreamFailure = _reflection.GeneratedProtocolMessageType('DownstreamFailure', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAMFAILURE,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:DownstreamFailure)
  })
_sym_db.RegisterMessage(DownstreamFailure)

DownstreamFailureAck = _reflection.GeneratedProtocolMessageType('DownstreamFailureAck', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAMFAILUREACK,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:DownstreamFailureAck)
  })
_sym_db.RegisterMessage(DownstreamFailureAck)

UpstreamFinish = _reflection.GeneratedProtocolMessageType('UpstreamFinish', (_message.Message,), {
  'DESCRIPTOR' : _UPSTREAMFINISH,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:UpstreamFinish)
  })
_sym_db.RegisterMessage(UpstreamFinish)

UpstreamFinishAck = _reflection.GeneratedProtocolMessageType('UpstreamFinishAck', (_message.Message,), {
  'DESCRIPTOR' : _UPSTREAMFINISHACK,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:UpstreamFinishAck)
  })
_sym_db.RegisterMessage(UpstreamFinishAck)

UpstreamFailure = _reflection.GeneratedProtocolMessageType('UpstreamFailure', (_message.Message,), {
  'DESCRIPTOR' : _UPSTREAMFAILURE,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:UpstreamFailure)
  })
_sym_db.RegisterMessage(UpstreamFailure)

UpstreamFailureAck = _reflection.GeneratedProtocolMessageType('UpstreamFailureAck', (_message.Message,), {
  'DESCRIPTOR' : _UPSTREAMFAILUREACK,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:UpstreamFailureAck)
  })
_sym_db.RegisterMessage(UpstreamFailureAck)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n0com.daimler.smartfactory.anne.streams.grpc.protoB\014StreamsProto'
  _STREAMINIT._serialized_start=28
  _STREAMINIT._serialized_end=79
  _STREAMCONDITIONS._serialized_start=81
  _STREAMCONDITIONS._serialized_end=122
  _STREAMINITCOMPLETE._serialized_start=124
  _STREAMINITCOMPLETE._serialized_end=168
  _DOWNSTREAMFINISH._serialized_start=170
  _DOWNSTREAMFINISH._serialized_end=188
  _DOWNSTREAMFINISHACK._serialized_start=190
  _DOWNSTREAMFINISHACK._serialized_end=211
  _DOWNSTREAMFAILURE._serialized_start=213
  _DOWNSTREAMFAILURE._serialized_end=247
  _DOWNSTREAMFAILUREACK._serialized_start=249
  _DOWNSTREAMFAILUREACK._serialized_end=271
  _UPSTREAMFINISH._serialized_start=273
  _UPSTREAMFINISH._serialized_end=289
  _UPSTREAMFINISHACK._serialized_start=291
  _UPSTREAMFINISHACK._serialized_end=310
  _UPSTREAMFAILURE._serialized_start=312
  _UPSTREAMFAILURE._serialized_end=344
  _UPSTREAMFAILUREACK._serialized_start=346
  _UPSTREAMFAILUREACK._serialized_end=366
# @@protoc_insertion_point(module_scope)
