# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nutil.proto\" \n\x04UUID\x12\x0b\n\x03msb\x18\x01 \x01(\x03\x12\x0b\n\x03lsb\x18\x02 \x01(\x03\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"-\n\x0cGrpcEndpoint\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x42\x36\n)com.daimler.smartfactory.anne.model.protoB\tUtilProtob\x06proto3')



_UUID = DESCRIPTOR.message_types_by_name['UUID']
_TIMESTAMP = DESCRIPTOR.message_types_by_name['Timestamp']
_GRPCENDPOINT = DESCRIPTOR.message_types_by_name['GrpcEndpoint']
UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:UUID)
  })
_sym_db.RegisterMessage(UUID)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

GrpcEndpoint = _reflection.GeneratedProtocolMessageType('GrpcEndpoint', (_message.Message,), {
  'DESCRIPTOR' : _GRPCENDPOINT,
  '__module__' : 'util_pb2'
  # @@protoc_insertion_point(class_scope:GrpcEndpoint)
  })
_sym_db.RegisterMessage(GrpcEndpoint)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.daimler.smartfactory.anne.model.protoB\tUtilProto'
  _UUID._serialized_start=14
  _UUID._serialized_end=46
  _TIMESTAMP._serialized_start=48
  _TIMESTAMP._serialized_end=91
  _GRPCENDPOINT._serialized_start=93
  _GRPCENDPOINT._serialized_end=138
# @@protoc_insertion_point(module_scope)
