
# Wenn die Aufnahmen im Ordner "Basisgerausche" auf deren durchschnittliches Maximum normalisiert werden sollen, auf True
# setzen, ansonsten auf False.
basisaudioNormalisierung : False

# Wenn die Störgeräusche im Ordner "Stoergerausche" im Verhältnis zum Basisgerausch normalisiert werden sollen auf True
# setzen, ansonsten auf False.
# Berechnungsformel: verarbeitetes Signal = Max(Basisgerausch)/Max(Noise) * Noise * stellwert[i] + Basisgerausch 
noiseNormalisierung : False

                
# Shifted den Frequenzbereich um pitchshiftSchrittweite% in den hoch- oder niedrigfrequenten.
pitchshiftSchrittweite: 0.1

# Der Wert 3 würde zur Erstellung der Liste von Verschiebungsstufen [-3,-2,-1,0,1,2,3] führen. Die Schrittweite ist 1.
pitchshiftSchritte: 10


# Anzahl der Abschnitte für das Entfernen von Frequenzanteilen
# 5 würde in [0,0.2,0.4,0.6,0.8,1] resultieren, wobei ein Intervall und der
# nächsttieferen Nummer besteht e.g. (0,0) (0-0.2),(0.2-0.4)...(0.8-1). Die Schrittweite ist 1/n.
# 0 ist ein valider Wert und würde dazu führen, dass diese Dimension in der Modifikation von Aufnahmen 
# nicht berücksichtigt wird. Die entsprechende Liste wäre [0].
frequenzSchritte : 5

# noiseSchritte ist die Anzahl der Elemente in dem Modifikationsarray.
# 5 würde [0,0.2,0.4,0.6,0.8,1] entsprechen --> Schrittweite: 1/n
# 0 ist ein valider Wert, wodurch diese Dimension nicht in der Modifikation von Aufnahmen berücksichtigt wird.
noiseSchritte : 5
# noiseAmplitude bestimmt wie stark das letztendlich überlagerte Geräusch am Ende sein soll.
# noiseAmplitude entspricht dem finalen Element der Liste --> [0,0.2,...,2] und bestimmt die Schrittweite
# in Form von noiseAmplitude/noiseSchritte.
# 0 ist ein valider Wert, wodurch diese Dimension nicht in der Modifikation von Aufnahmen berücksichtigt wird.
noiseAmplitude : 1

                